### PR TITLE
Add jump command

### PR DESCRIPTION
**Pull request by neojski**
This pull request implements a jump command that lets you quickly move to the logical parent nodes in your code.  It is very useful to quickly check the function you're in or even more useful to check the module you're in. One can also jump to let binding and match statement.

It is somehow related to #414.

I'm pretty sure that using `<localleader>j` in vim is a bad idea but I left it for testing. I'll wait for your suggestion.

I imagine people may want different keybinding for different sub commands. Because you can do `:MerlinJump target` where target is a subset of `fun,let,module,match`. For example @bmillwood was interested in just using `:MerlinJump module` and not really `:MerlinJump fun`. So we should make it easy to customize (or maybe just more detailed documentation would be enough for all vim/emacs magicians).

### CODE REVIEW

**Comment by neojski** [comment]
I just noticed that in this case:

```ocaml
let f a b =
  true
```

Assertion in `command.ml` is failing. So it's apparently not the case that every fun is immediately followed by pat. I'll investigate.

**Comment by neojski** [comment]
The issue is fixed now.

**Comment by neojski** [comment]
Ping @trefis, @def-lkb

**Comment by trefis** [comment]
We talked about this offline, @neojski will do some minor modifications then I'll merge.

**Comment by neojski** [comment]
I moved the command to a separate file and did the small changes you asked for. I think it's pretty much ready now.

Ping @trefis

**Comment by Drup** [comment]
Hum, documentation ? Also, why not add default bindings ?

**Comment by trefis** [comment]
> Hum, documentation ?

Good one.

> Also, why not add default bindings ?

Because default bindings are evil.
People are always complaining about bindings. Just choose your own!

**Comment by Drup** [comment]
> Because default bindings are evil.
> People are always complaining about bindings. Just choose your own!

I don't disagree, but then you *really* need the documentation. :D

**Comment by neojski** [comment]
@Drup, sorry about the lack of documentation. A rudimentary one you can find in the merlin-jump function description for emacs. I plan to prepare a screencast of this feature soon!

**Pull request merged**
