### PR TITLE
Rename vim commands that take very common names

### PR DESCRIPTION
**Pull request by rgrinberg**
Destruct, Locate, ILocate, Outline, Occurences, Rename, Reload all now
take a mandatory Merlin prefix

Mitigates #379 somewhat

### CODE REVIEW

**Comment by trefis** [comment]
I agree with #379 and #381 in principle, but now that these are there I am a bit worried about changing them/removing them.
I really like the flag idea mentioned in #381 however, but I would like the bindings to be here by default and the command names not to be prefixed by default; so current users who don't have a problem with them and are used to them, are not bothered at all.
(How about `g:merlin_clean_integration`?)

Also, why did you only rename a subset of the commands?

**Comment by trefis** [comment]
Ping @def-lkb btw, what do you think?

**Comment by rgrinberg** [comment]
I've only done it to the ones are already causing me problems and the ones that will surely cause more. The rest are not too pretty but I can live with for now.

I don't like the flag idea because it sounds kind of confusing and is not really the custom for any vim plugins i'm familiar with. If users want shorter names then they should use some [alias plugin](https://github.com/coot/cmdalias_vim) to accomplish that. The breakage this PR introduces is really minor IMO as well so it really doesn't like it's worth it.

**Comment by rgrinberg** [comment]
@def-lkb ?

**Comment by def-lkb** [comment]
There is a tension between new users wanting out-of-the-box configuration and more seasoned one wanting customization. I get #379, #381, #384 are all about this problem.

What about defining an initialization function setting easy defaults, which you can redefine to opt-out/fine-tune?

**Comment by rgrinberg** [comment]
@def-lkb I'm not quite sure how this particular issue is a "new vs experienced" user issue. I don't quite see how prefixing merlin commands would be anymore difficult. I do understand that this is a breaking change and users would potentially have to look at the docs again and remap tweak their key mappings. As intrusive as that is, I think it's a vastly better option than being incompatible with other common plugins out there.

As for making this configurable, I've already stated my reservations against it but I agree that it's still better than the current situation. I'll update the PR accordingly.

**Comment by trefis** [comment]
Superseded by 1094f99b .

Thanks!

**Pull request closed without merging**
