### PR TITLE
A version of merlin that works with trunk

### PR DESCRIPTION
**Pull request by trefis**
I had to work a bit on trunk recently and the experience was atrocious since merlin wasn't working.
I tried to revive #291 but trunk diverged quite a lot since then so I started again from scratch (but for the record, the method Mehdi used is the right one).

I have one big import commit and then about one commit per file to add "merlin's changes" on the raw compiler sources. So it should be easy to review for people who want to review it, or it could guide people to support newer versions of caml in the future (but hopefully from now on we will keep up to date with trunk so that won't be needed).

It currently builds with trunk as of yesterday, and I'll try to keep it up-to-date.
Trying it should be as easy as pinning the trunk branch of merlin in opam.

@gasche @chambart @Drup : you should give it a try when you have the time. I just tried it on the flambda branch and it seemed to work fine.
From now on you should also feel free to open an issue when it breaks with trunk.

Cheers,

### CODE REVIEW

**Comment by gasche** [comment]
> I had to work a bit on trunk recently and the experience was atrocious since merlin wasn't working.

Hah! We only needed a change in your dog food provider.

I'll try to test this as soon as possible, many thanks.

**Comment by chambart** [comment]
You really made m y day. Thanks a lot !

**Comment by gasche** [comment]
Would you have a `.merlin` file to propose for upstream inclusion? It seems silly that each user has to rewrite his/own own.

**Comment by trefis** [comment]
Mine is simply
```
S ./otherlibs/unix
B ./otherlibs/unix

S ./otherlibs/graph
B ./otherlibs/graph

S ./otherlibs/dynlink
B ./otherlibs/dynlink

S ./otherlibs/str
B ./otherlibs/str

S ./otherlibs/threads
B ./otherlibs/threads

S ./otherlibs/systhreads
B ./otherlibs/systhreads

S ./otherlibs/bigarray
B ./otherlibs/bigarray

S ./otherlibs/num
B ./otherlibs/num

S ./utils
B ./utils

S ./driver
B ./driver

S ./asmcomp
B ./asmcomp

S ./parsing
B ./parsing

S ./toplevel
B ./toplevel

S ./lex
B ./lex

S ./stdlib
B ./stdlib

S ./typing
B ./typing

S ./bytecomp
B ./bytecomp
```

Generated simply with:
```
find . -name '*.cmt' -exec dirname {} \; | uniq | sed 's/\(.*\)/S \1\nB \1\n/'
```
(Yes, it's disgusting).

You might want to add some flags in there, I don't know which warning should be on or off for example.

**Pull request merged**
